import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { AlertTriangle, ArrowRight, Clock3, FolderKanban, ShieldCheck, TrendingUp, Upload, Users } from 'lucide-react'
import type { RolGestion } from '@/App'
const data=[
 {id:'PRY-026',name:'Portal de Evaluación de Desempeño',area:'Desarrollo Organizacional',progress:72,status:'Atención',due:'18 sep 2026'},
 {id:'PRY-031',name:'Automatización de Nómina Semanal',area:'Nóminas',progress:48,status:'En tiempo',due:'04 oct 2026'},
 {id:'PRY-018',name:'Modelo Operativo Gross Performance',area:'Operaciones',progress:89,status:'En riesgo',due:'29 ago 2026'},
]
export function Acceso({onEnter}:{onEnter:(r:RolGestion)=>void}) {
 return <main className="gestion-login"><section className="gestion-hero"><div className="flex items-center gap-3"><span className="gestion-logo">IC</span><b>Gestión IC</b></div><div><p className="gestion-kicker !text-blue-200">GESTIÓN CORPORATIVA · FY2026</p><h1>Los proyectos importantes,<br/>en un solo lugar.</h1><p>Solicita, prioriza y da seguimiento a iniciativas de más de 30 días con evidencia, responsables y trazabilidad completa.</p></div><small>● Entorno de demostración · Datos simulados</small></section><section className="grid place-items-center bg-white p-10"><div className="w-full max-w-md"><p className="gestion-kicker">PORTAL CORPORATIVO DE PROYECTOS</p><h2 className="mt-3 text-4xl font-semibold tracking-tight">Bienvenido</h2><p className="mt-2 text-sm text-slate-500">Selecciona un perfil para explorar Gestión IC.</p><div className="mt-8 space-y-3">{[
 ['usuario','U','Usuario','Solicitudes, proyectos y evidencias'],['lider','L','Líder de área','Aprobaciones, equipo y seguimiento'],['admin','A','Administrador','Gobierno, roles y portafolio']
 ].map(x=><button key={x[0]} onClick={()=>onEnter(x[0] as RolGestion)} className="gestion-role"><span>{x[1]}</span><div><b>{x[2]}</b><small>{x[3]}</small></div><ArrowRight className="h-4 w-4"/></button>)}</div><div className="mt-6 flex gap-3 rounded-xl bg-slate-50 p-4 text-xs text-slate-600"><ShieldCheck className="h-5 w-5 text-blue-600"/><span><b>Acceso corporativo</b><br/>La versión productiva utilizará Microsoft Entra ID.</span></div></div></section></main>
}
function Head({k,t,p,action}:{k:string;t:string;p:string;action?:React.ReactNode}){return <div className="mb-6 flex items-end justify-between gap-4"><div><p className="gestion-kicker">{k}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{t}</h1><p className="mt-1 text-sm text-slate-500">{p}</p></div>{action}</div>}
export function Resumen({rol}:{rol:RolGestion}) {
 const nav=useNavigate(),leader=rol!=='usuario';return <><Head k="LUNES, 17 DE AGOSTO" t={rol==='admin'?'Portafolio corporativo':rol==='lider'?'Hola, Jorge. Tu equipo requiere atención.':'Hola, Jorge. Estos son tus proyectos.'} p={leader?'Decisiones, avance y riesgos de las iniciativas de largo plazo.':'Da seguimiento a tus asignaciones y mantén la evidencia al día.'} action={<button className="gestion-secondary" onClick={()=>nav('/registrar')}>＋ Solicitar proyecto</button>}/>
 <div className="gestion-kpis">{[[FolderKanban,leader?12:3,'PROYECTOS ACTIVOS'],[Clock3,leader?3:8,leader?'POR AUTORIZAR':'ACTIVIDADES PENDIENTES'],[TrendingUp,'69%','AVANCE PROMEDIO'],[AlertTriangle,2,'REQUIEREN ATENCIÓN']].map(([I,v,l],i)=>{const Icon=I as typeof FolderKanban;return <article key={l as string}><span className={'gestion-icon gi'+i}><Icon className="h-5 w-5"/></span><div><small>{l as string}</small><b>{v as string|number}</b><p>{i===2?'↑ 7% este mes':'1 requiere atención'}</p></div></article>})}</div>
 <div className="grid gap-4 xl:grid-cols-[1.6fr_.9fr]"><section className="gestion-panel"><PanelTitle title="Proyectos prioritarios" subtitle="Iniciativas con actividad reciente o riesgo" action={()=>nav('/proyectos')}/>{data.map((p,i)=><div className="gestion-project-row" key={p.id}><span className={'project-mark pm'+i}>{p.area.slice(0,2).toUpperCase()}</span><div><b>{p.name}</b><small>{p.id} · {p.area}</small><div className="gestion-bar"><i style={{width:p.progress+'%'}}/></div></div><strong>{p.progress}%</strong><em className={'project-state ps'+i}>{p.status}</em><small><b>ENTREGA</b>{p.due}</small></div>)}</section><section className="gestion-panel"><PanelTitle title="Actividad reciente" subtitle="Últimos movimientos del portafolio"/><div className="space-y-5 p-5">{[['FA','Frances Aviña','agregó una evidencia'],['MO','Manuel Ortega','reportó un bloqueo'],['DJ','Daniela Juárez','envió una solicitud'],['JM','Jorge Mejía','validó el avance']].map(x=><div className="flex gap-3" key={x[1]}><span className="avatar-mini">{x[0]}</span><p className="text-xs text-slate-600"><b>{x[1]}</b> {x[2]}<small className="block text-[10px] text-slate-400">Actualización reciente</small></p></div>)}</div></section></div>
 {leader&&<div className="mt-4 flex justify-between rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm"><span><b>3 decisiones esperan tu revisión</b><small className="ml-3 text-amber-700">Dos solicitudes y una reprogramación.</small></span><button onClick={()=>nav('/bandeja')} className="font-semibold text-amber-700">Revisar pendientes →</button></div>}</>
}
function PanelTitle({title,subtitle,action}:{title:string;subtitle:string;action?:()=>void}){return <div className="gestion-panel-head"><div><b>{title}</b><small>{subtitle}</small></div>{action&&<button onClick={action}>Ver portafolio →</button>}</div>}
export function Proyectos({rol}:{rol:RolGestion}) {
 const[progress,setProgress]=useState(72),[open,setOpen]=useState(false);return <><Head k="EJECUCIÓN · PROYECTOS +30 DÍAS" t={rol==='usuario'?'Mis proyectos':'Portafolio de proyectos'} p="Avance calculado desde actividades, evidencia y validaciones."/><section className="gestion-panel p-6"><div className="flex gap-4 border-b pb-5"><span className="project-mark pm0 !h-12 !w-12">DO</span><div className="flex-1"><p className="gestion-kicker">PRY-026 · DESARROLLO ORGANIZACIONAL</p><h2 className="mt-1 text-xl font-semibold">Portal de Evaluación de Desempeño</h2><p className="text-sm text-slate-500">Digitalización integral del proceso de evaluación, objetivos y talento.</p></div><em className="project-state ps0 h-fit">Atención</em></div><div className="grid items-center gap-8 py-7 lg:grid-cols-[150px_1fr_220px]"><div className="progress-ring" style={{'--progress':progress*3.6+'deg'} as React.CSSProperties}><span><b>{progress}%</b><small>AVANCE</small></span></div><div className="space-y-5">{[['Planeación y arquitectura',100],['Desarrollo y persistencia',progress],['Pruebas y liberación',25]].map(x=><div key={x[0] as string}><div className="flex justify-between text-xs font-semibold"><span>{x[0]}</span><b>{x[1]}%</b></div><div className="gestion-bar mt-2"><i style={{width:x[1]+'%'}}/></div></div>)}</div><div className="grid grid-cols-2 gap-5">{[['RESPONSABLE','Jorge Mejía'],['PERIODO','08 jul — 18 sep'],['DURACIÓN','74 días'],['EVIDENCIAS','18 archivos']].map(x=><div key={x[0]}><small className="gestion-kicker">{x[0]}</small><b className="mt-1 block text-xs">{x[1]}</b></div>)}</div></div><div className="flex gap-2 border-t pt-5"><button className="gestion-primary" onClick={()=>setOpen(true)}>＋ Registrar avance</button><button className="gestion-secondary">Ver Gantt</button><button className="gestion-secondary">Evidencias · 18</button></div></section>
 {open&&<div className="gestion-modal"><form onSubmit={e=>{e.preventDefault();setOpen(false)}}><div className="flex justify-between"><div><p className="gestion-kicker">NUEVA ACTUALIZACIÓN</p><h2 className="text-xl font-semibold">Registrar avance</h2></div><button type="button" onClick={()=>setOpen(false)}>×</button></div><label>Porcentaje de avance <b className="float-right text-blue-600">{progress}%</b><input type="range" min="0" max="100" value={progress} onChange={e=>setProgress(+e.target.value)}/></label><label>Resumen del avance<textarea required placeholder="Describe qué se completó, resultados y siguientes pasos."/></label><label className="evidence-drop"><input type="file" multiple accept="image/*,.pdf,.doc,.docx,.xls,.xlsx"/><Upload/><b>Agregar evidencias</b><small>Fotografías, PDF y Office · Máximo 10 archivos</small></label><label>¿Existe algún bloqueo?<select><option>No, continúa conforme al plan</option><option>Sí, requiere atención del líder</option></select></label><div className="flex justify-end gap-2 border-t pt-4"><button type="button" className="gestion-secondary" onClick={()=>setOpen(false)}>Cancelar</button><button className="gestion-primary">Publicar actualización</button></div></form></div>}</>
}
const people=[['Jorge Mejía','Inteligencia de Negocios',82],['Daniela Juárez','Ventas',67],['Frances Aviña','Nóminas',54],['Manuel Ortega','Operaciones',91]] as const
export function Equipo(){return <><Head k="CAPACIDAD Y ASIGNACIÓN" t="Mi equipo" p="Balance de carga, proyectos y pendientes del área."/><div className="grid gap-4 md:grid-cols-2">{people.map((x,i)=><article className="gestion-panel p-5" key={x[0]}><div className="flex items-center gap-3"><span className="avatar-big">{x[0].split(' ').map(y=>y[0]).slice(0,2)}</span><div className="flex-1"><b>{x[0]}</b><small className="block text-xs text-slate-500">{x[1]}</small></div><em className="rounded-full bg-blue-50 px-2 py-1 text-[10px] text-blue-700">{x[2]}% carga</em></div><div className="gestion-bar mt-4"><i style={{width:x[2]+'%'}}/></div><div className="mt-5 flex justify-between border-t pt-4 text-xs"><span><b>{i+1}</b> proyectos</span><span><b>{i+3}</b> pendientes</span><button className="text-blue-700">Ver carga →</button></div></article>)}</div></>}
export function Administracion(){return <><Head k="GOBIERNO DEL PORTAL" t="Administración" p="Usuarios, roles, áreas y reglas del portafolio corporativo."/><div className="gestion-kpis">{[[Users,42,'USUARIOS ACTIVOS'],[FolderKanban,11,'ÁREAS CONFIGURADAS'],[ShieldCheck,14,'LÍDERES DE ÁREA'],[AlertTriangle,2,'ACCESOS POR REVISAR']].map(([I,v,l],i)=>{const Icon=I as typeof Users;return <article key={l as string}><span className={'gestion-icon gi'+i}><Icon className="h-5 w-5"/></span><div><small>{l as string}</small><b>{v as number}</b></div></article>})}</div><section className="gestion-panel overflow-auto"><PanelTitle title="Usuarios y permisos" subtitle="Roles, áreas y estado de acceso"/><table className="gestion-table"><thead><tr><th>USUARIO</th><th>ÁREA</th><th>ROL</th><th>CARGA</th><th>ESTADO</th></tr></thead><tbody>{people.map((x,i)=><tr key={x[0]}><td><b>{x[0]}</b><small>usuario{i+1}@intercon.com.mx</small></td><td>{x[1]}</td><td><select defaultValue={i===0?'Administrador':i===1?'Líder':'Usuario'}><option>Administrador</option><option>Líder</option><option>Usuario</option></select></td><td>{x[2]}%</td><td><span className="project-state ps1">● Activo</span></td></tr>)}</tbody></table></section></>}
